url: "https://nquirk.github.io"
baseurl: /timelinesite 

title: Nicholas Quirk
description: "I just wanna fly"
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.JPG"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]

background-img: "../img/intro-bg.jpg"

me-img: "/img/me3.png"


