url: http://nquirk.github.io/timelinesite
baseurl: /timeline-jekyll-theme 

# Site Settings
title: Nicholas Q
description: "Timeline is multipurpose, single page Jekyll theme that includes a timeline section."
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "default.JPG"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
